//! serve HTTP handlers.
pub mod audit;
pub mod backfill;
#[cfg(feature = "catalog")]
pub mod catalog;
pub mod changes;
pub mod dlq;
pub mod doctor;
pub mod health;
#[cfg(feature = "catalog")]
pub mod local_outputs;
pub mod logs;
pub mod plan;
#[cfg(feature = "catalog")]
pub mod preview;
pub mod reload;
pub mod runs;
pub mod schemas;
#[cfg(feature = "templates")]
pub mod templates;
#[cfg(feature = "catalog")]
pub mod usage;
pub mod verify;
pub mod whoami;
