//! Configuration for the Oracle sink.

use faucet_common_oracle::{OracleConnectionConfig, quote_ident_oracle, quote_table_oracle};
use faucet_core::{FaucetError, WriteMode, validate_batch_size};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

fn default_batch_size() -> usize {
    1000
}
fn default_max_connections() -> u32 {
    5
}
fn default_statement_timeout_secs() -> u64 {
    300
}
fn default_true() -> bool {
    true
}

/// What to do with record keys that don't match a table column (`auto_columns`).
#[derive(Clone, Copy, Debug, Serialize, Deserialize, JsonSchema, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum OnUnknownField {
    /// Log a one-shot warning and drop the unknown keys (default).
    #[default]
    Warn,
    /// Silently drop the unknown keys.
    Drop,
    /// Fail the write.
    Error,
}

/// How records map onto table columns.
#[derive(Clone, Debug, Serialize, Deserialize, JsonSchema, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum OracleColumnMapping {
    /// Map top-level JSON keys to same-named columns (default).
    AutoColumns {
        /// Handling for keys with no matching column.
        #[serde(default)]
        on_unknown_field: OnUnknownField,
    },
    /// Serialize each record to JSON text in a single `CLOB` column.
    JsonColumn {
        /// Column that receives the JSON text.
        column: String,
    },
}

impl Default for OracleColumnMapping {
    fn default() -> Self {
        Self::AutoColumns {
            on_unknown_field: OnUnknownField::Warn,
        }
    }
}

/// How record keys, `table`, `key` and the JSON column name map onto Oracle
/// identifiers, which are case-sensitive once quoted.
#[derive(Clone, Copy, Debug, Serialize, Deserialize, JsonSchema, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum IdentifierCase {
    /// Use names exactly as written (default) — `id` addresses a column
    /// created as `"id"`.
    #[default]
    Preserve,
    /// Upper-case every name, matching tables created with unquoted
    /// identifiers (`CREATE TABLE ORDERS (ID ...)`).
    Upper,
}

impl IdentifierCase {
    /// Apply this case rule to one name.
    pub fn apply(self, name: &str) -> String {
        match self {
            IdentifierCase::Preserve => name.to_string(),
            IdentifierCase::Upper => name.to_uppercase(),
        }
    }
}

/// Configuration for [`OracleSink`](crate::OracleSink).
#[derive(Clone, Serialize, Deserialize, JsonSchema)]
pub struct OracleSinkConfig {
    /// Connection settings (`connect_string` or `host` + `service_name`/`sid`).
    #[serde(flatten)]
    pub connection: OracleConnectionConfig,
    /// Target table, optionally owner-qualified (`APP.EVENTS`).
    pub table: String,
    /// How records map onto columns. Defaults to `auto_columns`.
    #[serde(default)]
    pub column_mapping: OracleColumnMapping,
    /// Identifier case rule. Defaults to `preserve`.
    #[serde(default)]
    pub identifier_case: IdentifierCase,
    /// Rows per array-DML execution. `0` sends the whole page at once.
    /// Defaults to 1000.
    #[serde(default = "default_batch_size")]
    pub batch_size: usize,
    /// Maximum pooled sessions. Defaults to 5.
    #[serde(default = "default_max_connections")]
    pub max_connections: u32,
    /// Per-round-trip call timeout in seconds (`0` disables). Defaults to 300.
    #[serde(default = "default_statement_timeout_secs")]
    pub statement_timeout_secs: u64,
    /// Create the target table when it does not exist. Defaults to `true`.
    ///
    /// `json_column` mode creates `("ID" NUMBER GENERATED BY DEFAULT AS IDENTITY
    /// PRIMARY KEY, <column> CLOB)` up front; `auto_columns` mode infers nullable
    /// columns from the first page (with a `PRIMARY KEY` over `key` for keyed
    /// writes).
    #[serde(default = "default_true")]
    pub create_table: bool,
    /// Write mode (`append` / `upsert` / `delete` / `overwrite`) + `key` /
    /// `delete_marker`. `upsert` / `delete` require `auto_columns`.
    #[serde(flatten)]
    pub write: faucet_core::WriteSpec,
}

impl std::fmt::Debug for OracleSinkConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("OracleSinkConfig")
            .field("connection", &self.connection)
            .field("table", &self.table)
            .field("column_mapping", &self.column_mapping)
            .field("identifier_case", &self.identifier_case)
            .field("batch_size", &self.batch_size)
            .field("max_connections", &self.max_connections)
            .field("statement_timeout_secs", &self.statement_timeout_secs)
            .field("create_table", &self.create_table)
            .field("write", &self.write)
            .finish()
    }
}

impl OracleSinkConfig {
    /// An append-mode, `auto_columns` config with defaults elsewhere.
    pub fn new(connection: OracleConnectionConfig, table: impl Into<String>) -> Self {
        Self {
            connection,
            table: table.into(),
            column_mapping: OracleColumnMapping::default(),
            identifier_case: IdentifierCase::default(),
            batch_size: default_batch_size(),
            max_connections: default_max_connections(),
            statement_timeout_secs: default_statement_timeout_secs(),
            create_table: true,
            write: faucet_core::WriteSpec::default(),
        }
    }

    /// Validate the fail-fast invariants.
    pub fn validate(&self) -> Result<(), FaucetError> {
        self.connection.validate()?;
        validate_batch_size(self.batch_size)?;
        self.write.validate()?;
        if self.table.trim().is_empty() {
            return Err(FaucetError::Config("oracle sink requires a `table`".into()));
        }
        quote_table_oracle(&self.table)?;
        if let OracleColumnMapping::JsonColumn { column } = &self.column_mapping {
            quote_ident_oracle(column)?;
        }
        for k in &self.write.key {
            quote_ident_oracle(k)?;
        }
        if matches!(self.write.write_mode, WriteMode::Upsert | WriteMode::Delete)
            && !matches!(self.column_mapping, OracleColumnMapping::AutoColumns { .. })
        {
            return Err(FaucetError::Config(
                "oracle sink: write_mode upsert/delete requires column_mapping: auto_columns \
                 (key columns must be real columns)"
                    .into(),
            ));
        }
        Ok(())
    }

    /// This config with [`identifier_case`](Self::identifier_case) applied to
    /// the table, the JSON column, `key` and the delete-marker field.
    pub fn normalized(&self) -> Self {
        let case = self.identifier_case;
        let mut out = self.clone();
        out.table = case.apply(&self.table);
        if let OracleColumnMapping::JsonColumn { column } = &mut out.column_mapping {
            *column = case.apply(column);
        }
        out.write.key = self.write.key.iter().map(|k| case.apply(k)).collect();
        if let Some(m) = &mut out.write.delete_marker {
            m.field = case.apply(&m.field);
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn conn() -> OracleConnectionConfig {
        OracleConnectionConfig::new("h", 1521, "S", "u", "p")
    }

    #[test]
    fn serde_defaults() {
        let cfg: OracleSinkConfig = serde_json::from_value(json!({
            "host": "h", "service_name": "S", "username": "u", "password": "p",
            "table": "APP.EVENTS"
        }))
        .unwrap();
        assert_eq!(cfg.batch_size, 1000);
        assert_eq!(cfg.max_connections, 5);
        assert_eq!(cfg.statement_timeout_secs, 300);
        assert!(cfg.create_table);
        assert_eq!(cfg.identifier_case, IdentifierCase::Preserve);
        assert_eq!(cfg.column_mapping, OracleColumnMapping::default());
        cfg.validate().unwrap();
    }

    #[test]
    fn mapping_round_trips() {
        let m: OracleColumnMapping =
            serde_json::from_value(json!({"type": "json_column", "column": "DATA"})).unwrap();
        assert_eq!(
            m,
            OracleColumnMapping::JsonColumn {
                column: "DATA".into()
            }
        );
        let m: OracleColumnMapping =
            serde_json::from_value(json!({"type": "auto_columns", "on_unknown_field": "error"}))
                .unwrap();
        assert_eq!(
            m,
            OracleColumnMapping::AutoColumns {
                on_unknown_field: OnUnknownField::Error
            }
        );
    }

    #[test]
    fn validate_rejects_bad_configs() {
        let mut cfg = OracleSinkConfig::new(conn(), " ");
        assert!(cfg.validate().is_err());
        cfg.table = "a.b.c".into();
        assert!(cfg.validate().is_err());
        cfg.table = "T".into();
        cfg.column_mapping = OracleColumnMapping::JsonColumn {
            column: "a\"".into(),
        };
        assert!(cfg.validate().is_err());
        cfg.column_mapping = OracleColumnMapping::JsonColumn {
            column: "DATA".into(),
        };
        cfg.write.write_mode = WriteMode::Upsert;
        cfg.write.key = vec!["ID".into()];
        assert!(cfg.validate().is_err(), "upsert needs auto_columns");
        cfg.column_mapping = OracleColumnMapping::default();
        cfg.validate().unwrap();
        cfg.write.key = vec!["I\"D".into()];
        assert!(cfg.validate().is_err());
        cfg.write.key = vec![];
        assert!(cfg.validate().is_err(), "upsert needs a key");
        cfg.write.write_mode = WriteMode::Append;
        cfg.batch_size = faucet_core::MAX_BATCH_SIZE + 1;
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn normalized_upper_cases_names() {
        let mut cfg = OracleSinkConfig::new(conn(), "app.events");
        cfg.identifier_case = IdentifierCase::Upper;
        cfg.column_mapping = OracleColumnMapping::JsonColumn {
            column: "data".into(),
        };
        cfg.write.key = vec!["id".into()];
        cfg.write.delete_marker = Some(faucet_core::DeleteMarker {
            field: "__op".into(),
            values: vec!["d".into()],
        });
        let n = cfg.normalized();
        assert_eq!(n.table, "APP.EVENTS");
        assert_eq!(
            n.column_mapping,
            OracleColumnMapping::JsonColumn {
                column: "DATA".into()
            }
        );
        assert_eq!(n.write.key, vec!["ID".to_string()]);
        assert_eq!(n.write.delete_marker.unwrap().field, "__OP");
        let p = OracleSinkConfig::new(conn(), "app.events").normalized();
        assert_eq!(p.table, "app.events");
    }

    #[test]
    fn debug_masks_password() {
        let cfg = OracleSinkConfig::new(
            OracleConnectionConfig::new("h", 1, "S", "u", "hunter2"),
            "T",
        );
        assert!(!format!("{cfg:?}").contains("hunter2"));
    }
}
