//! Live TLS (`amqps://`) against a `rabbitmq:3-management` broker (Docker)
//! with a throwaway CA generated by the `openssl` CLI.

#![cfg(feature = "tls")]

use faucet_common_rabbitmq::{RabbitMqAuth, RabbitMqConnectionConfig, RabbitMqTls, connect};
use std::path::{Path, PathBuf};
use std::process::Command;
use testcontainers::core::{IntoContainerPort, WaitFor};
use testcontainers::runners::AsyncRunner;
use testcontainers::{GenericImage, ImageExt};

const RABBIT_CONF: &str = "\
loopback_users.guest = false
listeners.tcp.default = 5672
listeners.ssl.default = 5671
ssl_options.cacertfile = /certs/ca.pem
ssl_options.certfile = /certs/server.pem
ssl_options.keyfile = /certs/server.key
ssl_options.verify = verify_none
ssl_options.fail_if_no_peer_cert = false
";

fn openssl(dir: &Path, args: &[&str]) {
    let status = Command::new("openssl")
        .args(args)
        .current_dir(dir)
        .status()
        .expect("openssl CLI available");
    assert!(status.success(), "openssl {args:?} failed");
}

fn make_certs() -> PathBuf {
    let dir = std::env::temp_dir().join(format!("faucet-rmq-certs-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    openssl(
        &dir,
        &[
            "req",
            "-x509",
            "-newkey",
            "rsa:2048",
            "-nodes",
            "-keyout",
            "ca.key",
            "-out",
            "ca.pem",
            "-days",
            "2",
            "-subj",
            "/CN=faucet-test-ca",
        ],
    );
    openssl(
        &dir,
        &[
            "req",
            "-newkey",
            "rsa:2048",
            "-nodes",
            "-keyout",
            "server.key",
            "-out",
            "server.csr",
            "-subj",
            "/CN=localhost",
        ],
    );
    std::fs::write(
        dir.join("ext.cnf"),
        "subjectAltName=DNS:localhost,IP:127.0.0.1\nbasicConstraints=CA:FALSE\n\
         keyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\n",
    )
    .unwrap();
    openssl(
        &dir,
        &[
            "x509",
            "-req",
            "-in",
            "server.csr",
            "-CA",
            "ca.pem",
            "-CAkey",
            "ca.key",
            "-CAcreateserial",
            "-out",
            "server.pem",
            "-days",
            "2",
            "-extfile",
            "ext.cnf",
        ],
    );
    dir
}

#[tokio::test(flavor = "multi_thread")]
async fn connects_over_verified_tls() {
    let certs = make_certs();
    let read = |f: &str| std::fs::read(certs.join(f)).unwrap();
    let container = GenericImage::new("rabbitmq", "3-management")
        .with_exposed_port(5671.tcp())
        .with_wait_for(WaitFor::message_on_stdout("Server startup complete"))
        .with_copy_to(
            "/etc/rabbitmq/rabbitmq.conf",
            RABBIT_CONF.as_bytes().to_vec(),
        )
        .with_copy_to("/certs/ca.pem", read("ca.pem"))
        .with_copy_to("/certs/server.pem", read("server.pem"))
        .with_copy_to("/certs/server.key", read("server.key"))
        .start()
        .await
        .expect("rabbitmq container start");
    let port = container.get_host_port_ipv4(5671).await.unwrap();

    let trusted = RabbitMqConnectionConfig {
        host: Some("localhost".into()),
        port: Some(port),
        auth: RabbitMqAuth::Plain {
            username: "guest".into(),
            password: "guest".into(),
        },
        tls: RabbitMqTls {
            enabled: true,
            ca_cert_path: Some(certs.join("ca.pem")),
            ..Default::default()
        },
        connect_timeout_secs: 10,
        ..Default::default()
    };
    let mut last_err = None;
    let mut conn = None;
    for _ in 0..30 {
        match connect(&trusted).await {
            Ok(c) => {
                conn = Some(c);
                break;
            }
            Err(e) => {
                last_err = Some(e);
                tokio::time::sleep(std::time::Duration::from_millis(500)).await;
            }
        }
    }
    let conn = conn.unwrap_or_else(|| panic!("TLS connect failed: {last_err:?}"));
    assert!(conn.status().connected());
    conn.close(200, "".into()).await.ok();

    let untrusted = RabbitMqConnectionConfig {
        tls: RabbitMqTls {
            enabled: true,
            ..Default::default()
        },
        ..trusted
    };
    assert!(
        connect(&untrusted).await.is_err(),
        "an unknown CA must fail certificate verification"
    );
    let _ = std::fs::remove_dir_all(&certs);
}
